### ISSUE TITLE
Open Visibility Items in Paul Volcker Papers MC279 Collection are not showing up in PULFA.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3903] opened 2020-05-18 13:16 UTC
Example:
https://figgy.princeton.edu/catalog/817a0aac-3e51-496c-ac09-761fb6b88336

https://findingaids.princeton.edu/collections/MC279/c253

**Comment by escowles** [comment] 2020-05-28 17:25
There were SVN merge conflicts and SVN account permissions preventing the changes from being committed. I've done that manually, so these changes should be published when PULFA updates tomorrow morning.

I've created https://github.com/pulibrary/princeton_ansible/issues/1543 to track fixing the user account configured to access SVN, so it can commit changes in the future.

@kelea99 Can you close this when you've verified that the updates actually got published?

**Comment by escowles** [comment] 2020-06-01 12:20
The cause of this was https://github.com/pulibrary/princeton_ansible/issues/1543 — tracking over there.

**Closed by escowles** 2020-06-01 12:20 UTC
Labels: bug, content
