### ISSUE TITLE
If a derivative fails to generate, it should throw an error.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2539] opened 2019-02-06 19:07 UTC
Right now it just continued silently, which made the job not retry.

**Comment by escowles** [comment] 2019-05-13 17:40
To replicate: break ImageMagick and try to generate derivatives.

**Comment by jrgriffiniii** [comment] 2019-05-17 16:48
I could not find a way to disable this on the CircleCI environment (uninstalling ImageMagick using Homebrew on my local development environment *did* trigger the failures needed to reproduce this), hence I am going to proceed with testing for this by just raising errors within the context of RSpec tests.

**Comment by jrgriffiniii** [comment] 2019-05-17 17:24
I'm uncertain if retriggering the job explicitly in this manner would be acceptable: https://github.com/pulibrary/figgy/compare/issues-2539-jrgriffiniii-derivative-failures#diff-dde2fa5f290a1e9acf995cfc327145afR15

**Comment by hackmastera** [comment] 2019-05-17 18:13
@jrgriffiniii hm. it seems like the ticket is asking for the error to make it all the way out so that sidekiq will re-run the job. Is there something up the stack that is stifling the error?

**Comment by jrgriffiniii** [comment] 2019-05-17 18:47
`MiniMagick::Error: ImageMagick/GraphicsMagick is not installed` is still being propagated up through the stack for `CreateDerivativesJob` (I assume that this is how the job restarts are triggered), I'll look to improve the work on the branch in order to ensure that nothing should be getting stifled.

**Comment by jrgriffiniii** [comment] 2019-06-10 19:51
This seems to be addressed by the changes proposed in https://github.com/pulibrary/figgy/pull/3040, with the understanding that this is just a different message for `MiniMagick::Error`.  I will proceed by adding this as an additional test case and closing https://github.com/pulibrary/figgy/pull/3048

**Closed** 2021-07-13 20:09 UTC
Labels: bug
