### ISSUE TITLE
Ephemera collections

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2669] opened 2019-03-04 14:15 UTC
Add support for adding ephemera folders to collections, by adding the collection dropdown menu back to the ephemera folder new/edit form.

**Comment by escowles** [comment] 2019-08-07 17:44
Requested by Anna Meerson.  Changing from question to regular ticket.

**Comment by tpendragon** [comment] 2019-10-08 19:09
Closed as a duplicate of #3388

**Closed by tpendragon** 2019-10-08 19:09 UTC
Labels: enhancement
