### ISSUE TITLE
GoogleDrive not working for numismatics user

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#3887] opened 2020-05-11 15:00 UTC
Numismatics lab user not able to connect their GoogleDrive account:

From Grant Bruner:

> This week I continued adding the written info for the coins of Otho and Vitellius into Figgy. I am having some difficulty, however, inputting coin photos for these images. I can follow each of your steps until I need to sign into the Google account to share the photos. Instead of allowing me to sign in, the link turns pink and does not open. I have tried switching internet browsers or having Google Drive open on my computer, but I keep receiving the same result. I have attached a screenshot for reference. Has another student assistant encountered this problem before?

**Comment by hackmastera** [comment] 2020-05-11 15:35
@eliotjordan can you add the screenshot?

**Comment by escowles** [comment] 2020-05-11 20:14
![Screen Shot 2020-05-11 at 4 02 21 PM](https://user-images.githubusercontent.com/856924/81607000-fa810a80-93a1-11ea-9f25-28255d1ffd94.png)
This is what I'm seeing in Brave and Chrome when I try to select Google Drive — the disabled "Authorized" button said "Sign In" and was dark pink, but did nothing when I clicked on it.

I thought maybe my Google sign-in/authorization was messing things up, so I retried in a private window, and got the same results.

**Comment by jrgriffiniii** [comment] 2020-05-12 05:49
When attempting this in the production environment, I find the following error logged:

```
details: "Not a valid origin for the client: https://figgy.princeton.edu has not been whitelisted for client ID 484835294878-9cg485q5tpqq6gna68ntntvnujt2dgt6.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."
error: "idpiframe_initialization_failed"
```

**Comment by jrgriffiniii** [comment] 2020-05-12 05:55
I've updated the whitelisted URI's permitted for JavaScript cross-origin requests, this should now be functioning in the production environment. I apologize for this.

**Comment by escowles** [comment] 2020-05-12 12:28
I now get as far as logging in to Google, but clicking the "Sign in" button does not work, and I see this error in the console:
```
Invalid 'X-Frame-Options' header encountered when loading 'https://docs.google.com/picker?protocol=gadgets&origin=https://figgy.prince…%7D))&rpcService=72qw444lao0z&rpctoken=3wmlmmicatng&thirdParty=true&ppli=1': 'ALLOW-FROM https://figgy.princeton.edu' is not a recognized directive. The header will be ignored.
```
<img width="853" alt="Screen Shot 2020-05-12 at 8 27 19 AM" src="https://user-images.githubusercontent.com/856924/81691254-86d71000-942a-11ea-8be4-4db4932ff094.png">

**Comment by jrgriffiniii** [comment] 2020-05-12 12:38
I am looking to reproduce this still, I'm not quite certain what might be triggering this.

**Comment by escowles** [comment] 2020-05-12 12:42
I should have said before that I'm clearly already signed into Google at this point — when I select Google Drive, it pops up a window where it allows me to select whether to use my Princeton or personal Google accounts. In both cases, I get the screen I posted above. So I assume there is a permissions issue where it can't access my account even though I am logged in.

**Comment by jrgriffiniii** [comment] 2020-05-12 12:48
`ALLOW FROM [uri]` is stated as a valid directive, but 
 https://cheatsheetseries.owasp.org/cheatsheets/Clickjacking_Defense_Cheat_Sheet.html#x-frame-options-header-types leads me to suspect that it may be disabled or supported if certain Chrome extensions are enabled.

**Comment by jrgriffiniii** [comment] 2020-05-12 13:01
Perhaps I'm not understanding this correctly, but it appears that some of the Google server responses are using this header, but Chrome has dropped this as deprecated: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options#Browser_compatibility

**Comment by jrgriffiniii** [comment] 2020-05-12 13:07
I am also finding this error logged in my console, but this doesn't seem to block me from accessing Drive contents:

![image](https://user-images.githubusercontent.com/1443986/81694979-02878b80-9430-11ea-8f75-3aa46e3b9cf5.png)

**Comment by jrgriffiniii** [comment] 2020-05-19 17:30
By introducing error logging and using a set of Google test credentials, I am now able to reproduce this:

![image](https://user-images.githubusercontent.com/1443986/82358736-f160f080-99d4-11ea-852f-4cb6ebd498f9.png)

**Comment by jrgriffiniii** [comment] 2020-05-19 20:55
I've managed to restructure the code base with https://github.com/jrgriffiniii/browse-everything-redux-react/tree/fixes-firefox-76, but I am still receiving the following error with a separate set of testing credentials from Google:

![image](https://user-images.githubusercontent.com/1443986/82377132-38f57580-99f1-11ea-8f2a-f320e5665f49.png)

This still *does* work for me in the staging environment, but given that the Google JavaScript which transmits these AJAX requests is minified, I cannot trace exactly where I can disable the header warning which I *suspect* is the problem:

![image](https://user-images.githubusercontent.com/1443986/82377252-66daba00-99f1-11ea-800a-45e54315bfab.png)

**Comment by jrgriffiniii** [comment] 2020-05-19 23:34
I've managed to get this working with a local, decompressed copy of the `gapi` JavaScript file. I'm going to attempt extending the configuration for Webpack in order to ensure that this can be consistently resolved by apps consuming the React UI.

**Comment by jrgriffiniii** [comment] 2020-05-20 06:18
https://github.com/samvera-labs/browse-everything-redux-react/compare/master...jrgriffiniii:fixes-firefox-76 and https://github.com/pulibrary/figgy/compare/issues-3892-jrgriffiniii-be-firefox advances this to the point where it is functioning for me. I will please need to test this someone just to confirm that this approach will work.

**Comment by hackmastera** [comment] 2020-05-20 13:27
Just tried on staging, where it appears to be deployed. Unfortunately I get the same result as Esmé, with the `x-frame-options` error. before that I also see `cb=gapi.loaded_1:79 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://docs.google.com') does not match the recipient window's origin ('https://figgy-staging.princeton.edu').`

**Comment by hackmastera** [comment] 2020-05-20 13:38
fyi, I turned off all extensions and cleared cache / cookies before trying. used Chrome.

**Comment by jrgriffiniii** [comment] 2020-05-20 13:54
Thank you for testing, and I am sorry to hear this. I now have more granular control over the gapi JavaScript, so I can try and continue to debug where this is failing (I might try to use BrowserStack with a set of Google Drive credentials if I can find a way to do this securely).

**Comment by jrgriffiniii** [comment] 2020-06-05 14:02
I am not able to reproduce this with my private account on BrowserStack:

![image](https://user-images.githubusercontent.com/1443986/83884931-9f79d380-a713-11ea-9eda-6637da7a7b87.png)

**Closed** 2020-12-04 21:08 UTC
Labels: bug
