### ISSUE TITLE
Either clean up or don't allow deletion of subject entries from the UI

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2603] opened 2019-02-19 18:13 UTC
Based on analysis of https://github.com/pulibrary/figgy/issues/2547 it seems that someone deleted a subject entry but it was still present on at least one ephemera folder.

**Comment by tpendragon** [comment] 2019-02-20 01:22
Closed as a duplicate of #241

**Closed by tpendragon** 2019-02-20 01:22 UTC
