### ISSUE TITLE
I would like to be able to bulk download all tiff images from an item in figgy (like a manuscript).

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3910] opened 2020-05-18 23:31 UTC
@roelmoon currently uses the PUDL share to fulfill these requests (or a developer is asked to do so) for Manuscripts and the like. If there were a bulk download feature for the TIFFs in Figgy, it would simplify the process and make it possible for collection owners to provide content to patrons who have requested it in this way.

**Comment by tpendragon** [comment] 2020-06-22 18:21
Closed as a duplicate of #1891.

**Closed by tpendragon** 2020-06-22 18:21 UTC
Labels: feature, user-request
