### ISSUE TITLE
Enable CDL workflow for EAD objects

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4125] opened 2020-07-23 16:12 UTC
Allow certain items to be available for CDL workflow from EAD in PULFA.  

Objects should be checked out/queued/renewed/returned in the same manner as CDL items in the catalog.  Objects should have a configurable limited number of seats available for simultaneous access across a collection (for example, "3 simultaneous users can access everything that is digitized and made available for CDL in the Andre De Coppet Collection").

**Comment by tpendragon** [comment] 2020-07-23 17:17
## Possible Implementation Options

1. A new visibility setting along with a "CDL Concurrent Users" property
2. Just a "CDL Concurrent Users" property, along with a note that it will only apply if it's not a voyager item
3. Store the number of concurrent licenses in the EAD somehow.

**Comment by tpendragon** [comment] 2020-07-23 17:18
@kelynch To clarify, this isn't per item, but per collection? Is it per "Figgy Collection", or per EAD? If it's per Figgy collection, what happens if an item is a member of two collections? Is it one concurrent checkout per collection it's part of?

**Comment by kelynch** [comment] 2020-07-23 17:26
This is per EAD collection.  We may also be able to make the number of seats available be global across all EAD. @escowles is checking with stakeholders.

**Comment by kelynch** [comment] 2020-07-23 17:28
Wireframes ticket #4126

**Comment by escowles** [comment] 2020-07-29 12:24
The latest I have heard is that this is really "Limit access to certain Figgy items to a class". We could do that in a variety of ways:
* Access token links added to Canvas/BB course
* Add new role for class access and add the students enrolled in the course to that role in Figgy
* Add a notion of classes to Figgy, and check a list of course enrollment to allow/deny access (@kevinreiss Can we get a reliable list of students enrolled in a particular course?)

**Comment by tpendragon** [comment] 2020-07-30 15:07
The first option is most in line with what we do for music reserves right now.

**Comment by tpendragon** [comment] 2020-08-10 17:43
Closed as duplicate of #4169

**Closed by tpendragon** 2020-08-10 17:43 UTC
Labels: CDL-Queue, controlled-digital-lending
