### ISSUE TITLE
Create wireframes for indicating an item is checked out/available for CDL

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4143] opened 2020-08-03 14:39 UTC
Current example: https://catalog.princeton.edu/catalog/679947 

This should indicate that an item is available through CDL and provide a link to jump down the page to the CDL interface.

**Comment by tpendragon** [comment] 2020-08-04 17:44
Closed as duplicate of https://github.com/pulibrary/orangelight/issues/2171

**Closed by tpendragon** 2020-08-04 17:44 UTC
Labels: controlled-digital-lending
