### ISSUE TITLE
Cloud fixity failures for items no longer in Figgy

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#4078] opened 2020-07-10 15:28 UTC
Instead of erroring, we should check figgy to see if the item has been deleted and then... just carry on?

HB notice: https://app.honeybadger.io/projects/53391/faults/59168201

This honeybadger notice is gone, but to test this we can run the job on a non-existent ID.

## Success Criteria

Don't error if the object is gone.

**Comment by tpendragon** [comment] 2020-07-10 15:37
Is this a duplicate of https://github.com/pulibrary/figgy/issues/3814?

**Closed** 2023-01-25 21:46 UTC
Labels: preservation, honeybadger, work-cycle, on deck
