### ISSUE TITLE
Span tags visible in facet pop-up

### ISSUE THREAD

**Issue by kelynch** [pulibrary/figgy#4066] opened 2020-07-08 13:27 UTC
In Figgy, there are visible HTML span closing tags in the bottom portion of the faceted search "more>>" pop-up.  They appear once or twice in each pop-up.

Examples:

<img width="1266" alt="Screen Shot 2020-07-08 at 9 24 01 AM" src="https://user-images.githubusercontent.com/7795797/86924214-28ae6c80-c0fd-11ea-9e18-d294f7c1b722.png">

<img width="1266" alt="Screen Shot 2020-07-08 at 9 24 24 AM" src="https://user-images.githubusercontent.com/7795797/86924224-2ba95d00-c0fd-11ea-91a3-71bcc98f7264.png">

**Comment by christinach** [comment] 2020-07-08 13:31
duplicate of https://github.com/pulibrary/figgy/issues/4024

**Closed by christinach** 2020-07-08 13:31 UTC
Labels: bug
