### ISSUE TITLE
many Western Americana items were not ingested correctly

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/figgy#3584] opened 2020-01-10 19:06 UTC
@tpendragon reports that many items were not ingested correctly because SC had migrated a bunch of data to finding aids containers.

**Comment by tpendragon** [comment] 2020-02-10 18:57
@cwulfman Can we close this as a duplicate of the now-reopened #1702?

**Closed** 2020-02-11 14:12 UTC
Labels: bug, ingest
