### ISSUE TITLE
BrowseEverything ingest shouldn't fire if no files are selected.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4416] opened 2021-02-26 19:21 UTC
## Error

[Figgy/production] NoMethodError: undefined method `container_ids' for nil:NilClass

## Backtrace

    line 120 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: upload_files
    line 103 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: block in new_pending_uploads
    line 102 of [PROJECT_ROOT]/app/controllers/base_resource_controller.rb: map

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/63756895)

**Comment by hackartisan** [comment] 2021-08-11 15:44
Same error?

https://app.honeybadger.io/projects/53391/faults/80858477

**Comment by sdellis** [comment] 2021-11-18 16:11
Another similar error: 
https://app.honeybadger.io/projects/53391/faults/82303783

**Comment by hackartisan** [comment] 2021-12-01 19:18
duplicate of #4499

**Closed by hackartisan** 2021-12-01 19:18 UTC
Labels: bug, honeybadger
