### ISSUE TITLE
Logical structure does not work for MapSets

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#2377] opened 2019-01-04 20:44 UTC
Because of the way in which ScannedMaps are modeled, the structure manager saves the logical structure for MapSets in way that generates broken manifests. Specifically, the canvas id for a range with a ScannedMap does not match the id of the corresponding canvas.

**Comment by tpendragon** [comment] 2019-01-04 20:45
OH. Yes. We never fixed logical structure for sammelbands.

**Comment by tpendragon** [comment] 2019-01-04 20:45
Duplicate of #1554?

**Comment by eliotjordan** [comment] 2019-01-04 21:04
Maybe a dupe. I was working on fixing this at the wayfinder/controller level, which does not fix it for all sammelbands:

https://github.com/pulibrary/figgy/compare/2377-map-set-structure

Which mirrors logic in the manifest builder:

https://github.com/pulibrary/figgy/blob/master/app/services/manifest_builder.rb#L275

**Closed** 2019-01-07 16:04 UTC
Labels: Review
