### ISSUE TITLE
In Order Manager, I would like to select and auto-number multiple pages that have been shot and ingested two up (two pages in one frame). 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3768] opened 2020-03-20 15:05 UTC
Most recent use case for shooting items two-up: Thomas Keenan and a faculty member have requested two-up viewing for runs of historic soviet periodicals.  Although the viewer can always be changed to two up/paged viewing post-ingest, the problem comes in with the two page pictorial spreads within the periodicals that are not shot one-up, but two-up. A studio precedent to shoot two-up was set for two page spreads (that are not text based) for our digitized materials a while back. I share Thomas's reasoning for the request here:  _From a periodical studies standpoint recreating the physical object by showing how the 2-page spreads open up is important and it’s really difficult for a user to try to mentally recreate that looking at string of single pages._

**Comment by tpendragon** [comment] 2020-04-10 18:00
Closed as duplicate of #2822

**Closed by tpendragon** 2020-04-10 18:00 UTC
Labels: feature
