### ISSUE TITLE
Bootstrap 4: Back to search

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/figgy#5180] opened 2022-06-14 19:42 UTC
- Clicking back to search when viewing newly added map leads to this https://figgy-staging.princeton.edu/catalog.json?f%5Bsource_metadata_identifier_ssim%5D%5B%5D=cc&q=

**Comment by hackartisan** [comment] 2022-06-16 17:44
closing as duplicate of #4247

**Closed by hackartisan** 2022-06-16 17:44 UTC
Labels: work-cycle
