### ISSUE TITLE
Add functionality to support Right and Left justified text selections for Structure Manager sections

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#4971] opened 2022-02-03 22:20 UTC
### Summary
_As a researcher, I would like to see R->L script (Arabic, Persian, Ottoman Turkish, etc)  right-justified in the logical structure as seen in the index within the viewer_

This came up in a meeting with Deborah Schlein (NES librarian) and Joyce Bell (cataloger for Manuscripts of the Islamic World digital initiative).  It would be helpful to users to see R-L script such as Arabic, Persian, and Ottoman Turkish right-justified in the logical structure, that can be seen via the index of the viewer. 
### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._
There are no hard deadlines, nor is this stopping work.  This would improve user experience for those reading native script within the index of the viewer, added via structure manager in figgy.
### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked_

### Current behaviour
The added structure to an item is always left-justified.
### Requested behaviour
A Left or Right Justification selection option may be made available in structure manager within Figgy, with a default on left justification.

**Comment by tpendragon** [comment] 2023-04-04 19:27
Closed as duplicate of #5391

**Closed by tpendragon** 2023-04-04 19:27 UTC
Labels: user experience, user-request
