### ISSUE TITLE
New Role: Limited to viewing/creating/editing in one collection

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3246] opened 2019-08-02 14:03 UTC
Use case: external contributor to one collection.

Should be able to:
* create records attached to that collection and ingest files
* see other objects attached to that collection

Should not be able to:
* delete anything
* view objects not attached to that collection

**Comment by escowles** [comment] 2019-08-02 14:14
Two ephemera projects currently have this use case coming up (LAE and SAE).  There are a few other instances where external contributors have been discussed for other collections (Cicognara, Geniza).

**Comment by tpendragon** [comment] 2019-10-09 19:11
Closing as duplicate of #3398.

**Closed by tpendragon** 2019-10-09 19:11 UTC
Labels: enhancement, permissions, user-request
