### ISSUE TITLE
Refresh metadata for objects with PULFA source_metadata_identifiers

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#3375] opened 2019-09-16 14:32 UTC
We currently update items with Bib numbers, but not PULFA identifiers. We were concerned about the performance of updating metadata from PULFA, but I just ran this manually, and it updated 28k records in about 70 seconds.

**Comment by hackmastera** [comment] 2019-09-16 14:52
duplicate of #3155?

**Closed** 2019-09-16 14:55 UTC
