### ISSUE TITLE
Add 'Save and Ingest Another' to scanned resource form

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1547] opened 2018-07-23 13:47 UTC
This should copy over everything except title/portion note/local identifier/source metadata id as a first pass.

discussed at digital studio users meeting 7/19/2018

**Comment by tpendragon** [comment] 2019-10-03 20:35
Closed as a duplicate of #2463

**Closed by tpendragon** 2019-10-03 20:35 UTC
Labels: feature
