### ISSUE TITLE
Bulk Ingest not working

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#3791] opened 2020-04-09 11:37 UTC
@roelmoon attempt to ingest Lapidus items failed this week.

**Comment by jrgriffiniii** [comment] 2020-04-15 17:59
This will be fixed with the upgrade to BrowseEverything on https://github.com/pulibrary/figgy/pull/3754

**Comment by tpendragon** [comment] 2020-04-20 18:09
Closed as duplicate of #3604

**Closed by tpendragon** 2020-04-20 18:09 UTC
Labels: bug, ingest issues
