### ISSUE TITLE
Handle empty ids sent to GetResourcesByOrangelightIds

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2636] opened 2019-02-25 15:53 UTC
[Figgy/production] Sequel::DatabaseError: PG::SyntaxError: ERROR:  syntax error at end of inputLINE 2:         ^

If this gets an array with an empty string it errors.

## params

```
{
  "operationName" => "GetResourcesByOrangelightIds",
  "variables" => {"ids" => [""]},
  "query" => "query GetResourcesByOrangelightIds($ids: [String!]!) {\n resourcesByOrangelightIds(ids: $ids) {\n id\n thumbnail {\n iiifServiceUrl\n thumbnailUrl\n __typename\n }\n url\n members {\n id\n __typename\n }\n ... on ScannedResource {\n manifestUrl\n orangelightId\n __typename\n }\n ... on ScannedMap {\n manifestUrl\n orangelightId\n __typename\n }\n ... on Coin {\n manifestUrl\n orangelightId\n __typename\n }\n __typename\n }\n}\n",
  "format" => "json",
  "controller" => "graphql",
  "action" => "execute",
  "graphql" => {
    "operationName" => "GetResourcesByOrangelightIds",
    "variables" => {"ids" => [""]},
    "query" => "query GetResourcesByOrangelightIds($ids: [String!]!) {\n resourcesByOrangelightIds(ids: $ids) {\n id\n thumbnail {\n iiifServiceUrl\n thumbnailUrl\n __typename\n }\n url\n members {\n id\n __typename\n }\n ... on ScannedResource {\n manifestUrl\n orangelightId\n __typename\n }\n ... on ScannedMap {\n manifestUrl\n orangelightId\n __typename\n }\n ... on Coin {\n manifestUrl\n orangelightId\n __typename\n }\n __typename\n }\n}\n"
  }
}
```

## Backtrace
```
config/initializers/sequel_active_support_notification.rb:23:in `block in log_connection_yield'
config/initializers/sequel_active_support_notification.rb:17:in `log_connection_yield'
app/queries/find_many_by_property.rb:10:in `run_query'
app/queries/find_many_by_property.rb:17:in `find_many_by_property'
app/queries/find_by_source_metadata_identifier.rb:34:in `find_by_source_metadata_identifiers'
app/graphql/types/query_type.rb:56:in `resources_by_bibids'
app/graphql/types/query_type.rb:84:in `resources_by_orangelight_ids'
app/controllers/graphql_controller.rb:20:in `block in execute'
app/change_set_persisters/change_set_persister.rb:132:in `block (2 levels) in buffer_into_index'
app/change_set_persisters/change_set_persister.rb:185:in `with'
app/change_set_persisters/change_set_persister.rb:131:in `block in buffer_into_index'
app/adapters/indexing_adapter.rb:94:in `block (2 levels) in buffer_into_index'
app/adapters/indexing_adapter.rb:93:in `block in buffer_into_index'
app/adapters/indexing_adapter.rb:92:in `buffer_into_index'
app/change_set_persisters/change_set_persister.rb:130:in `buffer_into_index'
app/controllers/graphql_controller.rb:15:in `execute'
```

## Backtrace

    line 23 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: block in log_connection_yield
    line 17 of [PROJECT_ROOT]/config/initializers/sequel_active_support_notification.rb: log_connection_yield
    line 11 of [PROJECT_ROOT]/app/queries/find_many_by_string_property.rb: run_query

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/44300271)

**Comment by hackmastera** [comment] 2019-02-25 15:54
```
URL
POST https://figgy.princeton.edu/graphql
Location
production on figgy2
Referrer
http://127.0.0.1:40404/feedback
```
referrer is a feedback path?

**Comment by hackmastera** [comment] 2019-02-25 16:29
`bibIds` is set to `[]`; I can't exactly replicate this in dev just based on that; dev returns an `"Unexpected end of document"` error in the graphql response.

**Comment by hackmastera** [comment] 2019-02-25 16:43
I'm not sure how severe this bug is yet, not could I determine exactly the cause.

I think it may be related to recent work to support a [find multiple by property query](https://github.com/pulibrary/figgy/pull/2378/files) to support [orangelight code](https://github.com/pulibrary/orangelight/pull/1536) which was merged today.

**Closed** 2024-03-22 23:41 UTC
Labels: bug, honeybadger, maintenance / research
