### ISSUE TITLE
[Figgy/production] Sequel::DatabaseDisconnectError: PG::ConnectionBad: PQconsumeInput() SSL SYSCALL error: Connection timed out

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1938] opened 2018-10-01 13:21 UTC
## Backtrace

    line 76 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: block in buffer_into_index
    line 75 of [PROJECT_ROOT]/app/adapters/indexing_adapter.rb: buffer_into_index
    line 100 of [PROJECT_ROOT]/app/change_set_persisters/change_set_persister.rb: buffer_into_index

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39694894)

**Comment by hackmastera** [comment] 2018-10-01 13:22
This one is the error from `buffer_into_index`; there's another one just like it from `find_by`

**Comment by hackmastera** [comment] 2018-10-01 14:12
duplicate of https://github.com/pulibrary/figgy/issues/1928 this was fixed but just now deployed.

**Closed by hackmastera** 2018-10-01 14:12 UTC
