### ISSUE TITLE
[Figgy/production] NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1906] opened 2018-09-24 14:06 UTC
## Backtrace

    line 94 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save_all
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39606169)

**Comment by hackmastera** [comment] 2018-09-24 14:07
Why did reindex on prod suddenly start producing this error? we should resolve this or we risk being unable to reindex in an emergency.

**Comment by hackmastera** [comment] 2018-09-24 16:29
duplicate of #1881

**Closed by hackmastera** 2018-09-24 16:29 UTC
Labels: priority
