### ISSUE TITLE
Improve User Feedback on Ingest Status

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2447] opened 2019-01-18 00:52 UTC
Lots of questions on All-Hands 1/19 about when things are done, if they're done, and background processing that might be happening.

**Comment by hackmastera** [comment] 2019-05-13 18:52
potentially related to or duplicate of #638

**Comment by tpendragon** [comment] 2019-05-13 20:28
I think this is solved if FileSets know if they're done or not?

**Comment by escowles** [comment] 2019-05-13 20:37
I think a ScannedResource would also need to know if its FileSets are done, and a MVW would need to know if its volumes are done.

**Comment by tpendragon** [comment] 2019-05-13 20:39
Yeah, I think that's handled by "a parent isn't processed if its children aren't"

**Comment by escowles** [comment] 2019-05-13 20:43
👍 that sounds reasonable to me.

**Closed** 2019-05-17 18:54 UTC
Labels: all-hands-jan-2019
