### ISSUE TITLE
[Figgy/staging] MultiJson::ParseError: 765: unexpected token at 'Record 32101047381 not found or suppressed'

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1939] opened 2018-10-01 14:32 UTC
## Backtrace

    line 65 of [PROJECT_ROOT]/app/models/remote_record.rb: jsonld
    line 55 of [PROJECT_ROOT]/app/models/remote_record.rb: attributes
    line 143 of [PROJECT_ROOT]/app/models/archival_media_bag_parser.rb: remote_record_attributes

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/39705117)

**Comment by hackmastera** [comment] 2018-10-01 14:32
duplicate of #1930

**Closed by hackmastera** 2018-10-01 14:32 UTC
